import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  output: "export",
  trailingSlash: true,
  images: {
    // Static export: variants are pre-generated by
    // scripts/generate-image-variants.mjs and resolved by the loader.
    // imageSizes + deviceSizes must equal VARIANT_WIDTHS in
    // lib/image-variants.mjs.
    loader: "custom",
    loaderFile: "./lib/image-loader.ts",
    imageSizes: [128, 256],
    deviceSizes: [384, 640, 828, 1080, 1600],
  },
};

export default nextConfig;
