import type { NextConfig } from "next";
import { DEVICE_SIZES, IMAGE_SIZES } from "./lib/image-variants.mjs";

const nextConfig: NextConfig = {
  output: "export",
  trailingSlash: true,
  images: {
    // Static export: variants are pre-generated by
    // scripts/generate-image-variants.mjs and resolved by the loader.
    loader: "custom",
    loaderFile: "./lib/image-loader.ts",
    imageSizes: IMAGE_SIZES,
    deviceSizes: DEVICE_SIZES,
  },
};

export default nextConfig;
